/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpawnIndexRouteImport } from './routes/spawn/index'
import { Route as SpawnIdRouteImport } from './routes/spawn/$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpawnIndexRoute = SpawnIndexRouteImport.update({
  id: '/spawn/',
  path: '/spawn/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpawnIdRoute = SpawnIdRouteImport.update({
  id: '/spawn/$id',
  path: '/spawn/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/spawn/$id': typeof SpawnIdRoute
  '/spawn/': typeof SpawnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/spawn/$id': typeof SpawnIdRoute
  '/spawn': typeof SpawnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/spawn/$id': typeof SpawnIdRoute
  '/spawn/': typeof SpawnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/spawn/$id' | '/spawn/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/spawn/$id' | '/spawn'
  id: '__root__' | '/' | '/profile' | '/spawn/$id' | '/spawn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SpawnIdRoute: typeof SpawnIdRoute
  SpawnIndexRoute: typeof SpawnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spawn/': {
      id: '/spawn/'
      path: '/spawn'
      fullPath: '/spawn/'
      preLoaderRoute: typeof SpawnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spawn/$id': {
      id: '/spawn/$id'
      path: '/spawn/$id'
      fullPath: '/spawn/$id'
      preLoaderRoute: typeof SpawnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SpawnIdRoute: SpawnIdRoute,
  SpawnIndexRoute: SpawnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
